### ISSUE TITLE
Merge denso packages?

### ISSUE THREAD

**Issue by 130s** [fsuarez6/denso_simulator#1]
JSK lab at U-Tokyo made VS060 package at https://github.com/start-jsk/denso years ago upon the collaboration with Densowave. If you'd like to merge your great work there to optimize both our maintenance cost, we'll be happy to collaborate (of course no pressure). Thanks.

**Comment by fsuarez6** [comment]
@130s We are aware of JSK lab packages but we wanted to have 'light' packages with the minimum dependencies required to get the VS060 in gazebo. Moreover, we don't plan to develop any further these `denso_simulator` packages.

**Comment by 130s** [comment]
Good to know, I was just wondering!
